"""
Security Analytics models.

Contains models for security alerts generated by ML analysis or rule-based
detection, and threat summary reports for analyzed log files.
"""
import uuid

from django.db import models


class Alert(models.Model):
    """Security alert generated by ML analysis or rule-based detection."""

    ALERT_TYPE_CHOICES = [
        ('anomaly', 'Anomaly Detection'),
        ('suspicious_login', 'Suspicious Login'),
        ('brute_force', 'Brute Force Attack'),
        ('unusual_traffic', 'Unusual Traffic Pattern'),
    ]
    SEVERITY_CHOICES = [
        ('critical', 'Critical'),
        ('high', 'High'),
        ('medium', 'Medium'),
        ('low', 'Low'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    log_entry = models.ForeignKey(
        'logs.LogEntry',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='alerts',
    )
    log_file = models.ForeignKey(
        'logs.LogFile',
        on_delete=models.CASCADE,
        related_name='alerts',
    )
    alert_type = models.CharField(max_length=30, choices=ALERT_TYPE_CHOICES, db_index=True)
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, db_index=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    detection_method = models.CharField(max_length=100)
    confidence = models.FloatField(default=0.0)
    source_ip = models.GenericIPAddressField(null=True, blank=True)
    is_resolved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    metadata = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Alert'
        verbose_name_plural = 'Alerts'
        indexes = [
            models.Index(fields=['alert_type', 'severity']),
            models.Index(fields=['source_ip', 'created_at']),
            models.Index(fields=['is_resolved', 'severity']),
        ]

    def __str__(self):
        return f"[{self.get_severity_display()}] {self.title}"

    @property
    def severity_color(self):
        """Return a CSS-friendly color name for the severity level."""
        colors = {
            'critical': 'red',
            'high': 'orange',
            'medium': 'yellow',
            'low': 'blue',
        }
        return colors.get(self.severity, 'gray')


class ThreatSummary(models.Model):
    """Summary of threat analysis for a log file."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    log_file = models.OneToOneField(
        'logs.LogFile',
        on_delete=models.CASCADE,
        related_name='threat_summary',
    )
    total_events = models.IntegerField(default=0)
    total_alerts = models.IntegerField(default=0)
    critical_count = models.IntegerField(default=0)
    high_count = models.IntegerField(default=0)
    medium_count = models.IntegerField(default=0)
    low_count = models.IntegerField(default=0)
    top_source_ips = models.JSONField(default=list)
    risk_score_avg = models.FloatField(default=0.0)
    analysis_duration = models.FloatField(default=0.0)  # seconds
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Threat Summary'
        verbose_name_plural = 'Threat Summaries'

    def __str__(self):
        return f"Summary for {self.log_file.filename}"
