# Generated by Django 5.2.16 on 2026-07-15 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/logs/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('log_type', models.CharField(choices=[('apache', 'Apache'), ('nginx', 'Nginx'), ('auth', 'Linux Auth'), ('firewall', 'Firewall'), ('ssh', 'SSH'), ('auto', 'Auto-detect')], default='auto', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_entries', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log File',
                'verbose_name_plural': 'Log Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(default='UNKNOWN', max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, default='info', max_length=20)),
                ('description', models.TextField(default='')),
                ('raw_line', models.TextField()),
                ('line_number', models.IntegerField()),
                ('risk_score', models.FloatField(db_index=True, default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='logs.logfile')),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-timestamp', 'line_number'],
                'indexes': [models.Index(fields=['log_file', 'severity'], name='logs_logent_log_fil_e55f10_idx'), models.Index(fields=['log_file', 'timestamp'], name='logs_logent_log_fil_783c86_idx'), models.Index(fields=['source_ip', 'timestamp'], name='logs_logent_source__8f7604_idx')],
            },
        ),
    ]
