# Generated by Django 5.2.16 on 2026-07-15 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_events', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('top_source_ips', models.JSONField(default=list)),
                ('risk_score_avg', models.FloatField(default=0.0)),
                ('analysis_duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threat_summary', to='logs.logfile')),
            ],
            options={
                'verbose_name': 'Threat Summary',
                'verbose_name_plural': 'Threat Summaries',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('anomaly', 'Anomaly Detection'), ('suspicious_login', 'Suspicious Login'), ('brute_force', 'Brute Force Attack'), ('unusual_traffic', 'Unusual Traffic Pattern')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('detection_method', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('log_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='logs.logentry')),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='logs.logfile')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'severity'], name='analytics_a_alert_t_0b7cc9_idx'), models.Index(fields=['source_ip', 'created_at'], name='analytics_a_source__ea0101_idx'), models.Index(fields=['is_resolved', 'severity'], name='analytics_a_is_reso_037747_idx')],
            },
        ),
    ]
